// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.21.3
// source: api/resource.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ResourceType int32

const (
	ResourceType_RESOURCE_TYPE_UNKNOWN ResourceType = 0
	// Raspberry Pi Zero W
	ResourceType_RESOURCE_TYPE_RPI0W ResourceType = 1
	// Raspberry Pi Zero 2 W
	ResourceType_RESOURCE_TYPE_RPIZ2 ResourceType = 2
	// Raspberry Pi 2 Model B
	ResourceType_RESOURCE_TYPE_RPI21 ResourceType = 3
	// Raspberry Pi 3 Model A+
	ResourceType_RESOURCE_TYPE_RPI3AP ResourceType = 4
	// Raspberry Pi 3 Model B
	ResourceType_RESOURCE_TYPE_RPI32 ResourceType = 5
	// Raspberry Pi 3 Model B+
	ResourceType_RESOURCE_TYPE_RPI3BP ResourceType = 6
	// Raspberry Pi 4 Model B
	ResourceType_RESOURCE_TYPE_RPI4B ResourceType = 7
	// Raspberry Pi Pico W
	ResourceType_RESOURCE_TYPE_PICOW ResourceType = 8
)

// Enum value maps for ResourceType.
var (
	ResourceType_name = map[int32]string{
		0: "RESOURCE_TYPE_UNKNOWN",
		1: "RESOURCE_TYPE_RPI0W",
		2: "RESOURCE_TYPE_RPIZ2",
		3: "RESOURCE_TYPE_RPI21",
		4: "RESOURCE_TYPE_RPI3AP",
		5: "RESOURCE_TYPE_RPI32",
		6: "RESOURCE_TYPE_RPI3BP",
		7: "RESOURCE_TYPE_RPI4B",
		8: "RESOURCE_TYPE_PICOW",
	}
	ResourceType_value = map[string]int32{
		"RESOURCE_TYPE_UNKNOWN": 0,
		"RESOURCE_TYPE_RPI0W":   1,
		"RESOURCE_TYPE_RPIZ2":   2,
		"RESOURCE_TYPE_RPI21":   3,
		"RESOURCE_TYPE_RPI3AP":  4,
		"RESOURCE_TYPE_RPI32":   5,
		"RESOURCE_TYPE_RPI3BP":  6,
		"RESOURCE_TYPE_RPI4B":   7,
		"RESOURCE_TYPE_PICOW":   8,
	}
)

func (x ResourceType) Enum() *ResourceType {
	p := new(ResourceType)
	*p = x
	return p
}

func (x ResourceType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ResourceType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_resource_proto_enumTypes[0].Descriptor()
}

func (ResourceType) Type() protoreflect.EnumType {
	return &file_api_resource_proto_enumTypes[0]
}

func (x ResourceType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ResourceType.Descriptor instead.
func (ResourceType) EnumDescriptor() ([]byte, []int) {
	return file_api_resource_proto_rawDescGZIP(), []int{0}
}

type Resource struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type ResourceType `protobuf:"varint,1,opt,name=type,proto3,enum=api.ResourceType" json:"type,omitempty"`
	Name string       `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *Resource) Reset() {
	*x = Resource{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_resource_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Resource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Resource) ProtoMessage() {}

func (x *Resource) ProtoReflect() protoreflect.Message {
	mi := &file_api_resource_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Resource.ProtoReflect.Descriptor instead.
func (*Resource) Descriptor() ([]byte, []int) {
	return file_api_resource_proto_rawDescGZIP(), []int{0}
}

func (x *Resource) GetType() ResourceType {
	if x != nil {
		return x.Type
	}
	return ResourceType_RESOURCE_TYPE_UNKNOWN
}

func (x *Resource) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_api_resource_proto protoreflect.FileDescriptor

var file_api_resource_proto_rawDesc = []byte{
	0x0a, 0x12, 0x61, 0x70, 0x69, 0x2f, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x61, 0x70, 0x69, 0x22, 0x45, 0x0a, 0x08, 0x52, 0x65, 0x73,
	0x6f, 0x75, 0x72, 0x63, 0x65, 0x12, 0x25, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x11, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72,
	0x63, 0x65, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x2a, 0xf3, 0x01, 0x0a, 0x0c, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x54, 0x79, 0x70,
	0x65, 0x12, 0x19, 0x0a, 0x15, 0x52, 0x45, 0x53, 0x4f, 0x55, 0x52, 0x43, 0x45, 0x5f, 0x54, 0x59,
	0x50, 0x45, 0x5f, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x17, 0x0a, 0x13,
	0x52, 0x45, 0x53, 0x4f, 0x55, 0x52, 0x43, 0x45, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x52, 0x50,
	0x49, 0x30, 0x57, 0x10, 0x01, 0x12, 0x17, 0x0a, 0x13, 0x52, 0x45, 0x53, 0x4f, 0x55, 0x52, 0x43,
	0x45, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x52, 0x50, 0x49, 0x5a, 0x32, 0x10, 0x02, 0x12, 0x17,
	0x0a, 0x13, 0x52, 0x45, 0x53, 0x4f, 0x55, 0x52, 0x43, 0x45, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f,
	0x52, 0x50, 0x49, 0x32, 0x31, 0x10, 0x03, 0x12, 0x18, 0x0a, 0x14, 0x52, 0x45, 0x53, 0x4f, 0x55,
	0x52, 0x43, 0x45, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x52, 0x50, 0x49, 0x33, 0x41, 0x50, 0x10,
	0x04, 0x12, 0x17, 0x0a, 0x13, 0x52, 0x45, 0x53, 0x4f, 0x55, 0x52, 0x43, 0x45, 0x5f, 0x54, 0x59,
	0x50, 0x45, 0x5f, 0x52, 0x50, 0x49, 0x33, 0x32, 0x10, 0x05, 0x12, 0x18, 0x0a, 0x14, 0x52, 0x45,
	0x53, 0x4f, 0x55, 0x52, 0x43, 0x45, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x52, 0x50, 0x49, 0x33,
	0x42, 0x50, 0x10, 0x06, 0x12, 0x17, 0x0a, 0x13, 0x52, 0x45, 0x53, 0x4f, 0x55, 0x52, 0x43, 0x45,
	0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x52, 0x50, 0x49, 0x34, 0x42, 0x10, 0x07, 0x12, 0x17, 0x0a,
	0x13, 0x52, 0x45, 0x53, 0x4f, 0x55, 0x52, 0x43, 0x45, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x50,
	0x49, 0x43, 0x4f, 0x57, 0x10, 0x08, 0x42, 0x25, 0x5a, 0x23, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x65, 0x72, 0x64, 0x6f, 0x6e, 0x67, 0x6c, 0x69, 0x2f, 0x64, 0x69,
	0x73, 0x63, 0x6f, 0x74, 0x68, 0x65, 0x71, 0x75, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_resource_proto_rawDescOnce sync.Once
	file_api_resource_proto_rawDescData = file_api_resource_proto_rawDesc
)

func file_api_resource_proto_rawDescGZIP() []byte {
	file_api_resource_proto_rawDescOnce.Do(func() {
		file_api_resource_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_resource_proto_rawDescData)
	})
	return file_api_resource_proto_rawDescData
}

var file_api_resource_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_resource_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_api_resource_proto_goTypes = []interface{}{
	(ResourceType)(0), // 0: api.ResourceType
	(*Resource)(nil),  // 1: api.Resource
}
var file_api_resource_proto_depIdxs = []int32{
	0, // 0: api.Resource.type:type_name -> api.ResourceType
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_resource_proto_init() }
func file_api_resource_proto_init() {
	if File_api_resource_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_resource_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Resource); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_resource_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_resource_proto_goTypes,
		DependencyIndexes: file_api_resource_proto_depIdxs,
		EnumInfos:         file_api_resource_proto_enumTypes,
		MessageInfos:      file_api_resource_proto_msgTypes,
	}.Build()
	File_api_resource_proto = out.File
	file_api_resource_proto_rawDesc = nil
	file_api_resource_proto_goTypes = nil
	file_api_resource_proto_depIdxs = nil
}
